# Generated by Django 6.1.1 on 2026-09-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(db_index=True, default=1, max_length=20),
            preserve_default=False,
        ),
    ]
