# Generated by Django 6.1.1 on 2026-09-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('M', 'M'), ('L', 'L'), ('XXL', 'XXL'), ('XL', 'XL'), ('S', 'S')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
