# Generated by Django 6.1.1 on 2026-09-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_size_remove_product_size_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
